name: Merge PRs automatically

on:
  pull_request:
    types: [opened]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: auto-pull-request-merge
  # You may pin to the exact commit or the version.
  # uses: KeisukeYamashita/auto-pull-request-merge@68fa2d9d8e449e217aa37bda2e51e3e86ace3bfb
        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
          
